"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import "./console.css";

const sections = ["Overview", "Policies", "Approvals", "Agents", "Evidence", "MCP Gateway", "Reports"] as const;
type Section = (typeof sections)[number];

const syntheticQueues = [
  [["Partner case brief", "Disclosure", "High", "Awaiting review"], ["Policy exception", "Governance", "Medium", "Scope review"], ["Case triage route", "Operations", "Low", "Auto-approved"]],
  [["Evidence bundle", "Records", "Medium", "Provenance check"], ["Guidance retrieval", "Knowledge", "Low", "Allowed"], ["Agency share", "Disclosure", "High", "Awaiting review"]],
  [["Report draft", "Casework", "Low", "Auto-approved"], ["Records scope", "Authority", "Medium", "Policy check"], ["Bulk export", "Records", "High", "Blocked"]]
];

const fictionalMissions = [
  { title: "Source coverage review", purpose: "Check fictional aggregate-source coverage before a recommendation is displayed.", steps: ["Scope registered", "Synthetic provenance checked", "Coverage uncertainty retained"] },
  { title: "Policy scope check", purpose: "Test a fictional request against identity, purpose, classification, and least-privilege boundaries.", steps: ["Purpose checked", "Policy boundary applied", "Review path selected"] },
  { title: "Evidence package review", purpose: "Prepare a fictional evidence package that keeps verified facts separate from unknowns.", steps: ["Sources linked", "Conflicts marked", "Human review prepared"] },
  { title: "Low-risk administrative route", purpose: "Route a fictional, reversible administrative task without a financial or enforcement outcome.", steps: ["Risk boundary checked", "Reversible action confirmed", "Audit event recorded"] }
];

const fictionalOutcomes = [
  { label: "Allowed in fictional scope", tone: "allowed", explanation: "The synthetic request matched its limited purpose and data classification." },
  { label: "Held for fictional human review", tone: "review", explanation: "The synthetic request crossed a review boundary and stopped for an accountable person." },
  { label: "Blocked by fictional policy", tone: "blocked", explanation: "The synthetic request exceeded the demo agent’s permitted scope." },
  { label: "Auto-routed, low risk", tone: "automatic", explanation: "The synthetic task is reversible, administrative, and recorded for review." }
];

const controlViews: Record<Exclude<Section, "Overview">, { eyebrow: string; title: string; description: string; use: string; flow: string[]; cards: [string, string, string][] }> = {
  Policies: { eyebrow: "POLICY CONTROL PLANE", title: "Policy coverage and enforcement", description: "A synthetic view of how every proposed agent action is matched to purpose, authority, classification, and a human-review boundary.", use: "Use this view to explain which rules govern an action and why the system allowed, held, or blocked it.", flow: ["Purpose", "Authority", "Policy", "Decision"], cards: [["Active controls", "Default-deny and least privilege", "Synthetic control set"], ["Review triggers", "Disclosure, money, rights, or enforcement", "Human decision required"], ["Policy output", "Explainable rationale", "Integrity-linked"]] },
  Approvals: { eyebrow: "ACCOUNTABLE REVIEW", title: "Approvals and review boundaries", description: "A fictional queue that separates routine work from actions that require an accountable human reviewer.", use: "Use this view to demonstrate how high-impact decisions stop before execution and become reviewable evidence.", flow: ["Request", "Risk check", "Reviewer", "Record"], cards: [["Review queue", "Synthetic requests awaiting authority", "Role-bound"], ["Decision rights", "Approve, reject, or return", "Human accountable"], ["Appeal trail", "Decision and rationale preserved", "Forensic record"]] },
  Agents: { eyebrow: "AGENT GOVERNANCE", title: "Agents, identity, and permitted work", description: "A synthetic representation of scoped agent identities rather than autonomous actors with unlimited system access.", use: "Use this view to show that each agent receives only the tools, data classes, and mission scope it needs.", flow: ["Identity", "Role", "Tool scope", "Audit"], cards: [["Identity proof", "Fictional workload identity verified", "Tenant-scoped"], ["Tool grants", "Approved MCP tools only", "Least privilege"], ["Autonomy limit", "Reversible admin tasks only", "Review-gated"]] },
  Evidence: { eyebrow: "FORENSIC EVIDENCE", title: "Evidence integrity and provenance", description: "A fictional evidence chain that records source coverage, conflicts, decision rationale, and the limits of each conclusion.", use: "Use this view to show investigators and auditors what supports a result, what remains unknown, and who made each decision.", flow: ["Source", "Verify", "Link", "Challenge"], cards: [["Source register", "Approved synthetic sources", "Provenance checked"], ["Conflict handling", "Unknowns remain visible", "No false certainty"], ["Integrity chain", "Linked fictional event timeline", "Tamper-evident concept"]] },
  "MCP Gateway": { eyebrow: "GOVERNED TOOL ACCESS", title: "MCP Gateway control surface", description: "A synthetic tool registry showing the trust layer between an agent and each approved MCP capability.", use: "Use this view to explain how tool discovery and every call are filtered, explained, and logged.", flow: ["Agent", "Gateway", "Policy", "MCP tool"], cards: [["Registry", "Approved fictional tools", "Availability rotates"], ["Evaluation", "Scope and purpose checked", "Policy rationale"], ["Outcome", "Allow, review, block, or route", "Audit event"]] },
  Reports: { eyebrow: "DECISION REPORTING", title: "Reports for oversight and learning", description: "A fictional reporting surface designed for accountable operations, not performance theater or predictive scoring of people.", use: "Use this view to show leaders a reviewable summary of policy activity, review workload, and system limits.", flow: ["Events", "Summarize", "Review", "Export"], cards: [["Leadership brief", "Synthetic policy and review trends", "No personal data"], ["Investigation pack", "Fictional evidence timeline", "Challengeable"], ["Control report", "Coverage and exception patterns", "Improvement loop"]] }
};

export default function TrustConsole() {
  const [selected, setSelected] = useState<Section>("Overview");
  const [seed, setSeed] = useState(101);
  const [missionRun, setMissionRun] = useState(0);
  const [telemetryCycle, setTelemetryCycle] = useState(1);
  const rand = (min: number, max: number, salt: number) => min + ((seed * 29 + salt * 13) % (max - min + 1));
  const queue = syntheticQueues[seed % syntheticQueues.length];
  const mission = fictionalMissions[(seed + missionRun) % fictionalMissions.length];
  const outcome = fictionalOutcomes[(seed * 3 + missionRun) % fictionalOutcomes.length];
  const generateCycle = () => { setSeed(Math.floor(Math.random() * 9999) + 1); setMissionRun(current => current + 1); setTelemetryCycle(current => current + 1); };

  useEffect(() => {
    const timer = window.setInterval(() => { setSeed(Math.floor(Math.random() * 9999) + 1); setTelemetryCycle(current => current + 1); }, 4200);
    return () => window.clearInterval(timer);
  }, []);

  return <main className="console-page"><aside className="console-side"><Link className="console-brand" href="/">◈ <span>Agentic Trust Layer</span></Link><p>CONTROL CENTER</p>{sections.map(item => <button key={item} className={selected === item ? "selected" : ""} onClick={() => setSelected(item)}>{item}</button>)}<div className="synthetic">SYNTHETIC ENVIRONMENT<br /><strong>Fictional national demo</strong></div></aside><section className="console-main"><header><div><p className="kicker">{selected.toUpperCase()} / FICTIONAL DATA</p><h1>Trust Operations Console</h1></div><div className="header-actions"><button onClick={generateCycle}>Generate fictional mission cycle</button><Link href="/">Return to Trust Lab</Link></div></header><div className="notice">This is a simulated interface. It uses fictional scenarios only; no records, people, agencies, or risk signals are real.</div>{selected === "Overview" ? <Overview seed={seed} cycle={telemetryCycle} rand={rand} queue={queue} mission={mission} outcome={outcome} generateCycle={generateCycle} /> : <ControlCenter section={selected} view={controlViews[selected]} cycle={telemetryCycle} rand={rand} generateCycle={generateCycle} />}</section></main>;
}

function Overview({ seed, cycle, rand, queue, mission, outcome, generateCycle }: { seed: number; cycle: number; rand: (min: number, max: number, salt: number) => number; queue: string[][]; mission: typeof fictionalMissions[number]; outcome: typeof fictionalOutcomes[number]; generateCycle: () => void }) { return <><section className="mission-cycle"><div><p className="kicker">FICTIONAL MISSION CYCLE</p><h2>{mission.title}</h2><p>{mission.purpose}</p><div className="mission-steps">{mission.steps.map((step,index) => <span key={step}><b>{index + 1}</b>{step}</span>)}</div></div><div className="mission-outcome"><p>SIMULATED OUTPUT · CYCLE {cycle}</p><strong className={outcome.tone}>{outcome.label}</strong><span>{outcome.explanation}</span><small>Human authority remains required for consequential decisions.</small><button onClick={generateCycle}>Generate another fictional outcome <span>↻</span></button></div></section><OverviewLiveFeed cycle={cycle} rand={rand} /><section className="metrics"><Metric label="Protected agents" value={String(rand(18,52,1))} note="All identities verified" /><Metric label="Policies active" value={String(rand(96,184,2))} note="Default-deny enabled" /><Metric label="Pending approvals" value={String(rand(1,7,3))} note="Human review required" /><Metric label="Audit integrity" value="100%" note="Evidence chain verified" /></section><OverviewDigest cycle={cycle} rand={rand} queue={queue} /><section className="console-grid"><article className="console-card approvals"><div className="card-heading"><div><p className="kicker">ROTATING REVIEW QUEUE</p><h2>Approvals requiring attention</h2></div><span>{rand(1,5,4)} pending</span></div>{queue.map(([name, type, risk, status],index) => <div className="approval-row" key={`${name}-${seed}`}><div><strong>{index ? `${name} ${rand(10,99,index + 10)}` : name}</strong><small>{type}</small></div><em className={risk.toLowerCase()}>{risk}</em><span>{status}</span></div>)}</article><article className="console-card evidence"><p className="kicker">FORENSIC EVIDENCE</p><h2>Decision activity</h2><div className="bars">{Array.from({length:7},(_,index) => rand(35,90,index + 20)).map((height,index) => <i key={index} style={{height:`${height}%`}} />)}</div><div className="legend"><span>● Allowed</span><span>● Review</span><span>● Denied</span></div></article></section></> }

function OverviewDigest({ cycle, rand, queue }: { cycle: number; rand: (min: number, max: number, salt: number) => number; queue: string[][] }) { const approval = queue[0]; const reportStates = ["Ready for oversight", "Evidence exceptions summarized", "Review workload briefed"]; return <section className="overview-digest"><div className="digest-heading"><div><p className="kicker">CONTROL CENTER SNAPSHOT · AUTO-REFRESH {cycle}</p><h2>Fictional operational posture</h2></div><span><i /> Local synthetic telemetry</span></div><div className="digest-grid"><article className="digest-card digest-policy"><div className="digest-label"><span>Policies</span><b>◫</b></div><strong>{rand(94,186,130)} active controls</strong><div className="mini-rule"><i style={{width:`${rand(64,96,131)}%`}} /></div><small>Default-deny coverage · {rand(88,99,132)}%</small></article><article className="digest-card digest-approval"><div className="digest-label"><span>Approvals</span><b>✓</b></div><strong>{approval[0]}</strong><p>{approval[1]} · <em>{approval[2]} risk</em></p><small>{approval[3]} · accountable reviewer required</small></article><article className="digest-card digest-agents"><div className="digest-label"><span>Agents</span><b>◌</b></div><strong>{rand(18,52,133)} protected identities</strong><div className="agent-dots"><i /><i /><i /><i /><i /></div><small>Scoped tools and mission-bound roles</small></article><article className="digest-card digest-evidence"><div className="digest-label"><span>Evidence</span><b>⌁</b></div><strong>Integrity chain verified</strong><div className="chain-nodes"><i /><i /><i /><i /></div><small>{rand(26,89,134)} fictional provenance links retained</small></article><article className="digest-card digest-mcp"><div className="digest-label"><span>MCP Gateway</span><b>⌘</b></div><strong>{rand(4,8,135)} governed tools online</strong><div className="mcp-lanes"><i /><i /><i /></div><small>{rand(82,99,136)}% policy match · every call audit-linked</small></article><article className="digest-card digest-report"><div className="digest-label"><span>Reports</span><b>▤</b></div><strong>{reportStates[cycle % reportStates.length]}</strong><div className="report-lines"><i /><i /><i /></div><small>Fictional leadership brief · no personal data</small></article></div></section>; }

function OverviewLiveFeed({ cycle, rand }: { cycle: number; rand: (min: number, max: number, salt: number) => number }) { return <section className="overview-live"><div><p>LIVE FICTIONAL OPERATIONS · AUTO-REFRESH {cycle}</p><strong><i /> Trusted activity stream</strong><small>Mission telemetry refreshed locally. No external records are read.</small></div><div className="overview-flow"><span>Identity</span><b>→</b><span>Policy</span><b>→</b><span>Review</span><b>→</b><span>Evidence</span></div><div className="overview-pulse"><strong>{rand(82,99,91)}%</strong><span>synthetic control health</span></div></section>; }

function ControlCenter({ section, view, cycle, rand, generateCycle }: { section: Exclude<Section, "Overview">; view: typeof controlViews[Exclude<Section, "Overview">]; cycle: number; rand: (min: number, max: number, salt: number) => number; generateCycle: () => void }) {
  if (section === "MCP Gateway") return <GatewayControlCenter view={view} rand={rand} generateCycle={generateCycle} />;
  return <section className="control-center"><div className="control-intro"><p className="kicker">{view.eyebrow}</p><h2>{view.title}</h2><p>{view.description}</p><button onClick={generateCycle}>Generate fictional {view.title.toLowerCase()} output <span>↻</span></button><small className="control-cycle"><i /> New synthetic output cycle {cycle} · refreshes every few seconds</small></div><UniqueGraphic section={section} rand={rand} /><LiveControlLayer section={section} cycle={cycle} rand={rand} /><div className="control-cards">{view.cards.map(([label, detail, status]) => <article key={label}><p>{label}</p><h3>{detail}</h3><span>{status}</span></article>)}</div><aside className="control-use"><p>HOW TO USE THIS VIEW</p><strong>{view.use}</strong><span>Every number, event, and outcome shown here is fictional and generated locally.</span></aside></section>;
}

function LiveControlLayer({ section, cycle, rand }: { section: Exclude<Section, "Overview" | "MCP Gateway">; cycle: number; rand: (min: number, max: number, salt: number) => number }) { const profiles: Record<Exclude<Section, "Overview" | "MCP Gateway">, { labels: [string, string, string]; events: string[]; mode: string }> = { Policies: { labels: ["Policies evaluated", "Exceptions held", "Coverage"], events: ["Purpose rule recalculated", "Least-privilege check renewed", "Default-deny boundary confirmed"], mode: "ruleset refresh" }, Approvals: { labels: ["Queued", "Reviewer-ready", "Decision receipt"], events: ["Reviewer role verified", "Decision lane refreshed", "Appeal trace attached"], mode: "review rotation" }, Agents: { labels: ["Scoped agents", "Tool grants", "Autonomy posture"], events: ["Workload identity renewed", "Tool grant constrained", "Reversible task route checked"], mode: "agent scope refresh" }, Evidence: { labels: ["Sources linked", "Integrity checks", "Challenge paths"], events: ["Provenance hash renewed", "Conflict marker retained", "Evidence receipt signed"], mode: "integrity scan" }, Reports: { labels: ["Briefs generated", "Oversight trends", "Control follow-ups"], events: ["Oversight brief regenerated", "Exception trend recomputed", "Improvement action queued"], mode: "reporting refresh" } }; const profile = profiles[section]; const [a,b,c] = profile.labels; const active = cycle % profile.events.length; return <section className={`live-control-layer live-${section.toLowerCase()}`}><div className="live-layer-heading"><div><p>LIVE FICTIONAL TELEMETRY · CYCLE {cycle}</p><h3>{section} activity pulse</h3></div><span><i /> {profile.mode}</span></div><div className="live-layer-body"><div className="live-layer-orbit"><b>{rand(62,96,102)}%</b><small>within simulated<br />control boundary</small><i /><i /><i /></div><div className="live-layer-metrics"><span><b>{rand(12,68,103)}</b>{a}</span><span><b>{rand(1,9,104)}</b>{b}</span><span><b>{rand(88,100,105)}%</b>{c}</span></div><div className="live-layer-stream"><p>ACTIVE SYNTHETIC EVENTS</p>{profile.events.map((event,index) => <span className={index === active ? "event-active" : ""} key={event}>{index === active ? "●" : "✓"} {event}</span>)}</div></div><div className="live-layer-progress"><span style={{ width: `${rand(35,92,120)}%` }} /><small>Cycle {cycle} · locally generated telemetry</small></div></section>; }

function GatewayControlCenter({ view, rand, generateCycle }: { view: typeof controlViews["MCP Gateway"]; rand: (min: number, max: number, salt: number) => number; generateCycle: () => void }) {
  const states = ["Allowed", "Review", "Blocked", "Auto-routed"] as const;
  const tools = ["case_guidance.read", "evidence_package.prepare", "partner_share.request", "records_scope.check"];
  const currentState = states[rand(0, states.length - 1, 51)];
  const currentTool = tools[rand(0, tools.length - 1, 52)];
  const statusClass = currentState === "Allowed" ? "allowed" : currentState === "Review" ? "review" : currentState === "Blocked" ? "blocked" : "automatic";
  return <section className="gateway-center"><div className="gateway-hero"><div><p className="kicker">{view.eyebrow} / LIVE FICTIONAL FLOW</p><h2>{view.title}</h2><p>{view.description}</p><div className="gateway-live"><span className="gateway-live-dot" /> FICTITIOUS GATEWAY ACTIVE <small>Auto-refreshing synthetic telemetry</small></div><button onClick={generateCycle}>Run a fictional gateway cycle <span>↻</span></button></div><div className="gateway-run-card"><p>CURRENT FICTIONAL CALL</p><strong>{currentTool}</strong><div className="gateway-run-route"><span>Agent</span><b>→</b><span className="gateway-node">Trust<br />Gateway</span><b>→</b><span>Approved<br />tool</span></div><em className={statusClass}>{currentState}</em><small>Policy rationale and audit receipt attached</small></div></div><div className="gateway-dashboard"><article className="gateway-registry"><div className="gateway-card-header"><div><p>APPROVED TOOL REGISTRY</p><h3>Fictional capability posture</h3></div><span>{rand(4,8,53)} active</span></div>{tools.map((tool,index) => { const state = states[(rand(0, 999, 60) + index) % states.length]; const style = state === "Allowed" ? "allowed" : state === "Review" ? "review" : state === "Blocked" ? "blocked" : "automatic"; return <div className="gateway-tool-row" key={tool}><span className="tool-orb">⌘</span><div><strong>{tool}</strong><small>{["Knowledge", "Evidence", "Disclosure", "Records"][index]} · fictional governed tool</small></div><em className={style}>{state}</em></div>; })}</article><article className="gateway-pulse"><p>LIVE DECISION PULSE</p><h3>{rand(68,97,54)}% <span>policy match</span></h3><div className="pulse-bars">{Array.from({ length: 12 }, (_, index) => <i key={index} style={{ height: `${rand(28,92,index + 70)}%` }} />)}</div><div className="pulse-summary"><span><b>{rand(12,39,55)}</b> evaluated</span><span><b>{rand(1,7,56)}</b> held for review</span><span><b>100%</b> audit-linked</span></div></article><article className="gateway-audit"><p>FORENSIC RECEIPT</p><div className="audit-hash"><b>✓</b><span>Integrity chain<br /><strong>verified</strong></span></div><div className="audit-lines"><span>purpose: fictional-casework</span><span>authority: policy-limited</span><span>record: linked-{rand(1000,9999,57)}</span></div><small>Every result remains explainable, reviewable, and synthetic.</small></article></div><aside className="gateway-use"><div><p>HOW TO USE THIS VIEW</p><strong>{view.use}</strong></div><div><p>SAFETY BOUNDARY</p><span>Financial, enforcement, and rights-affecting actions stay human-review-gated.</span></div><div><p>DEMO NOTE</p><span>All tools, calls, metrics, and receipts are fictional and generated locally.</span></div></aside></section>;
}

function UniqueGraphic({ section, rand }: { section: Exclude<Section, "Overview">; rand: (min: number, max: number, salt: number) => number }) {
  if (section === "Policies") return <div className="unique-graphic policy-graphic"><p>FICTIONAL POLICY STACK</p><div className="policy-layers"><span>Mission purpose</span><span>Role authority</span><span>Data classification</span><span>Human review boundary</span></div><div className="policy-score"><strong>{rand(82,98,4)}%</strong><small>synthetic policy coverage</small></div></div>;
  if (section === "Approvals") return <div className="unique-graphic approvals-graphic"><p>FICTIONAL REVIEW LANES</p><div className="approval-lanes"><span><b>01</b> Routine<br /><small>Auto-route</small></span><span><b>02</b> Review<br /><small>Human decision</small></span><span><b>03</b> Restricted<br /><small>Policy hold</small></span></div><strong>{rand(2,8,8)} fictional cases waiting for accountable review</strong></div>;
  if (section === "Agents") return <div className="unique-graphic agents-graphic"><p>SCOPED AGENT CONSTELLATION</p><div className="agent-orbit"><i>Case guide</i><i>Evidence prep</i><i>Policy check</i><b>Trust<br />layer</b></div><small>{rand(3,7,12)} fictional agents · no unrestricted tool access</small></div>;
  if (section === "Evidence") return <div className="unique-graphic evidence-graphic"><p>INTEGRITY-LINKED EVIDENCE CHAIN</p><div className="evidence-chain"><span>Source</span><b>→</b><span>Provenance</span><b>→</b><span>Conflict</span><b>→</b><span>Record</span></div><div className="hash-lines"><i /><i /><i /><i /></div><small>Fictional chain status: intact and challengeable</small></div>;
  if (section === "MCP Gateway") return <div className="unique-graphic gateway-graphic"><p>GOVERNED MCP TOPOLOGY</p><div className="gateway-map"><span>Agent</span><b>Trust<br />Gateway</b><span>Tool<br />registry</span><span>Audit<br />record</span></div><small>{rand(3,8,14)} synthetic tools exposed · every call evaluated</small></div>;
  return <div className="unique-graphic reports-graphic"><p>OVERSIGHT REPORT BOARD</p><div className="report-sheets"><span><b>Policy</b><i /></span><span><b>Review</b><i /></span><span><b>Evidence</b><i /></span></div><div className="report-bars"><i style={{height:`${rand(35,88,16)}%`}} /><i style={{height:`${rand(35,88,17)}%`}} /><i style={{height:`${rand(35,88,18)}%`}} /><i style={{height:`${rand(35,88,19)}%`}} /></div></div>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
