"use client";

import { useEffect, useState } from "react";
import "./console.css";

const sections = ["Overview", "Policies", "Approvals", "Agents", "Evidence", "MCP Gateway", "Reports"] as const;
type Section = (typeof sections)[number];

const syntheticQueues = [
  [["Partner case brief", "Disclosure", "High", "Awaiting review"], ["Policy exception", "Governance", "Medium", "Scope review"], ["Case triage route", "Operations", "Low", "Auto-approved"]],
  [["Evidence bundle", "Records", "Medium", "Provenance check"], ["Guidance retrieval", "Knowledge", "Low", "Allowed"], ["Agency share", "Disclosure", "High", "Awaiting review"]],
  [["Report draft", "Casework", "Low", "Auto-approved"], ["Records scope", "Authority", "Medium", "Policy check"], ["Bulk export", "Records", "High", "Blocked"]]
];

const fictionalMissions = [
  { title: "Source coverage review", purpose: "Check fictional aggregate-source coverage before a recommendation is displayed.", steps: ["Scope registered", "Synthetic provenance checked", "Coverage uncertainty retained"] },
  { title: "Policy scope check", purpose: "Test a fictional request against identity, purpose, classification, and least-privilege boundaries.", steps: ["Purpose checked", "Policy boundary applied", "Review path selected"] },
  { title: "Evidence package review", purpose: "Prepare a fictional evidence package that keeps verified facts separate from unknowns.", steps: ["Sources linked", "Conflicts marked", "Human review prepared"] },
  { title: "Low-risk administrative route", purpose: "Route a fictional, reversible administrative task without a financial or enforcement outcome.", steps: ["Risk boundary checked", "Reversible action confirmed", "Audit event recorded"] }
];

const fictionalOutcomes = [
  { label: "Allowed in fictional scope", tone: "allowed", explanation: "The synthetic request matched its limited purpose and data classification." },
  { label: "Held for fictional human review", tone: "review", explanation: "The synthetic request crossed a review boundary and stopped for an accountable person." },
  { label: "Blocked by fictional policy", tone: "blocked", explanation: "The synthetic request exceeded the demo agent’s permitted scope." },
  { label: "Auto-routed, low risk", tone: "automatic", explanation: "The synthetic task is reversible, administrative, and recorded for review." }
];

const controlViews: Record<Exclude<Section, "Overview">, { eyebrow: string; title: string; description: string; use: string; flow: string[]; cards: [string, string, string][] }> = {
  Policies: { eyebrow: "POLICY CONTROL PLANE", title: "Policy coverage and enforcement", description: "A synthetic view of how every proposed agent action is matched to purpose, authority, classification, and a human-review boundary.", use: "Use this view to explain which rules govern an action and why the system allowed, held, or blocked it.", flow: ["Purpose", "Authority", "Policy", "Decision"], cards: [["Active controls", "Default-deny and least privilege", "Synthetic control set"], ["Review triggers", "Disclosure, money, rights, or enforcement", "Human decision required"], ["Policy output", "Explainable rationale", "Integrity-linked"]] },
  Approvals: { eyebrow: "ACCOUNTABLE REVIEW", title: "Approvals and review boundaries", description: "A fictional queue that separates routine work from actions that require an accountable human reviewer.", use: "Use this view to demonstrate how high-impact decisions stop before execution and become reviewable evidence.", flow: ["Request", "Risk check", "Reviewer", "Record"], cards: [["Review queue", "Synthetic requests awaiting authority", "Role-bound"], ["Decision rights", "Approve, reject, or return", "Human accountable"], ["Appeal trail", "Decision and rationale preserved", "Forensic record"]] },
  Agents: { eyebrow: "AGENT GOVERNANCE", title: "Agents, identity, and permitted work", description: "A synthetic representation of scoped agent identities rather than autonomous actors with unlimited system access.", use: "Use this view to show that each agent receives only the tools, data classes, and mission scope it needs.", flow: ["Identity", "Role", "Tool scope", "Audit"], cards: [["Identity proof", "Fictional workload identity verified", "Tenant-scoped"], ["Tool grants", "Approved MCP tools only", "Least privilege"], ["Autonomy limit", "Reversible admin tasks only", "Review-gated"]] },
  Evidence: { eyebrow: "FORENSIC EVIDENCE", title: "Evidence integrity and provenance", description: "A fictional evidence chain that records source coverage, conflicts, decision rationale, and the limits of each conclusion.", use: "Use this view to show investigators and auditors what supports a result, what remains unknown, and who made each decision.", flow: ["Source", "Verify", "Link", "Challenge"], cards: [["Source register", "Approved synthetic sources", "Provenance checked"], ["Conflict handling", "Unknowns remain visible", "No false certainty"], ["Integrity chain", "Linked fictional event timeline", "Tamper-evident concept"]] },
  "MCP Gateway": { eyebrow: "GOVERNED TOOL ACCESS", title: "MCP Gateway control surface", description: "A synthetic tool registry showing the trust layer between an agent and each approved MCP capability.", use: "Use this view to explain how tool discovery and every call are filtered, explained, and logged.", flow: ["Agent", "Gateway", "Policy", "MCP tool"], cards: [["Registry", "Approved fictional tools", "Availability rotates"], ["Evaluation", "Scope and purpose checked", "Policy rationale"], ["Outcome", "Allow, review, block, or route", "Audit event"]] },
  Reports: { eyebrow: "DECISION REPORTING", title: "Reports for oversight and learning", description: "A fictional reporting surface designed for accountable operations, not performance theater or predictive scoring of people.", use: "Use this view to show leaders a reviewable summary of policy activity, review workload, and system limits.", flow: ["Events", "Summarize", "Review", "Export"], cards: [["Leadership brief", "Synthetic policy and review trends", "No personal data"], ["Investigation pack", "Fictional evidence timeline", "Challengeable"], ["Control report", "Coverage and exception patterns", "Improvement loop"]] }
};

export default function TrustConsole() {
  const [selected, setSelected] = useState<Section>("Overview");
  const [seed, setSeed] = useState(101);
  const [missionRun, setMissionRun] = useState(0);
  const rand = (min: number, max: number, salt: number) => min + ((seed * 29 + salt * 13) % (max - min + 1));
  const queue = syntheticQueues[seed % syntheticQueues.length];
  const mission = fictionalMissions[(seed + missionRun) % fictionalMissions.length];
  const outcome = fictionalOutcomes[(seed * 3 + missionRun) % fictionalOutcomes.length];
  const generateCycle = () => { setSeed(Math.floor(Math.random() * 9999) + 1); setMissionRun(current => current + 1); };

  useEffect(() => {
    const timer = window.setInterval(() => setSeed(Math.floor(Math.random() * 9999) + 1), 9000);
    return () => window.clearInterval(timer);
  }, []);

  return <main className="console-page"><aside className="console-side"><a className="console-brand" href="/">◈ <span>Agentic Trust Layer</span></a><p>CONTROL CENTER</p>{sections.map(item => <button key={item} className={selected === item ? "selected" : ""} onClick={() => setSelected(item)}>{item}</button>)}<div className="synthetic">SYNTHETIC ENVIRONMENT<br /><strong>Fictional national demo</strong></div></aside><section className="console-main"><header><div><p className="kicker">{selected.toUpperCase()} / FICTIONAL DATA</p><h1>Trust Operations Console</h1></div><div className="header-actions"><button onClick={generateCycle}>Generate fictional mission cycle</button><a href="/">Return to Trust Lab</a></div></header><div className="notice">This is a simulated interface. It uses fictional scenarios only; no records, people, agencies, or risk signals are real.</div>{selected === "Overview" ? <Overview seed={seed} rand={rand} queue={queue} mission={mission} outcome={outcome} generateCycle={generateCycle} /> : <ControlCenter section={selected} view={controlViews[selected]} seed={seed} rand={rand} generateCycle={generateCycle} />}</section></main>;
}

function Overview({ seed, rand, queue, mission, outcome, generateCycle }: { seed: number; rand: (min: number, max: number, salt: number) => number; queue: string[][]; mission: typeof fictionalMissions[number]; outcome: typeof fictionalOutcomes[number]; generateCycle: () => void }) { return <><section className="mission-cycle"><div><p className="kicker">FICTIONAL MISSION CYCLE</p><h2>{mission.title}</h2><p>{mission.purpose}</p><div className="mission-steps">{mission.steps.map((step,index) => <span key={step}><b>{index + 1}</b>{step}</span>)}</div></div><div className="mission-outcome"><p>SIMULATED OUTPUT</p><strong className={outcome.tone}>{outcome.label}</strong><span>{outcome.explanation}</span><small>Human authority remains required for consequential decisions.</small><button onClick={generateCycle}>Generate another fictional outcome <span>↻</span></button></div></section><section className="metrics"><Metric label="Protected agents" value={String(rand(18,52,1))} note="All identities verified" /><Metric label="Policies active" value={String(rand(96,184,2))} note="Default-deny enabled" /><Metric label="Pending approvals" value={String(rand(1,7,3))} note="Human review required" /><Metric label="Audit integrity" value="100%" note="Evidence chain verified" /></section><section className="console-grid"><article className="console-card approvals"><div className="card-heading"><div><p className="kicker">ROTATING REVIEW QUEUE</p><h2>Approvals requiring attention</h2></div><span>{rand(1,5,4)} pending</span></div>{queue.map(([name, type, risk, status],index) => <div className="approval-row" key={`${name}-${seed}`}><div><strong>{index ? `${name} ${rand(10,99,index + 10)}` : name}</strong><small>{type}</small></div><em className={risk.toLowerCase()}>{risk}</em><span>{status}</span></div>)}</article><article className="console-card evidence"><p className="kicker">FORENSIC EVIDENCE</p><h2>Decision activity</h2><div className="bars">{Array.from({length:7},(_,index) => rand(35,90,index + 20)).map((height,index) => <i key={index} style={{height:`${height}%`}} />)}</div><div className="legend"><span>● Allowed</span><span>● Review</span><span>● Denied</span></div></article></section></> }

function ControlCenter({ section, view, seed, rand, generateCycle }: { section: Exclude<Section, "Overview">; view: typeof controlViews[Exclude<Section, "Overview">]; seed: number; rand: (min: number, max: number, salt: number) => number; generateCycle: () => void }) { return <section className="control-center"><div className="control-intro"><p className="kicker">{view.eyebrow}</p><h2>{view.title}</h2><p>{view.description}</p><button onClick={generateCycle}>Generate fictional {view.title.toLowerCase()} output <span>↻</span></button></div><UniqueGraphic section={section} seed={seed} rand={rand} /><div className="control-cards">{view.cards.map(([label, detail, status]) => <article key={label}><p>{label}</p><h3>{detail}</h3><span>{status}</span></article>)}</div><aside className="control-use"><p>HOW TO USE THIS VIEW</p><strong>{view.use}</strong><span>Every number, event, and outcome shown here is fictional and generated locally.</span></aside></section> }

function UniqueGraphic({ section, seed, rand }: { section: Exclude<Section, "Overview">; seed: number; rand: (min: number, max: number, salt: number) => number }) {
  if (section === "Policies") return <div className="unique-graphic policy-graphic"><p>FICTIONAL POLICY STACK</p><div className="policy-layers"><span>Mission purpose</span><span>Role authority</span><span>Data classification</span><span>Human review boundary</span></div><div className="policy-score"><strong>{rand(82,98,4)}%</strong><small>synthetic policy coverage</small></div></div>;
  if (section === "Approvals") return <div className="unique-graphic approvals-graphic"><p>FICTIONAL REVIEW LANES</p><div className="approval-lanes"><span><b>01</b> Routine<br /><small>Auto-route</small></span><span><b>02</b> Review<br /><small>Human decision</small></span><span><b>03</b> Restricted<br /><small>Policy hold</small></span></div><strong>{rand(2,8,8)} fictional cases waiting for accountable review</strong></div>;
  if (section === "Agents") return <div className="unique-graphic agents-graphic"><p>SCOPED AGENT CONSTELLATION</p><div className="agent-orbit"><i>Case guide</i><i>Evidence prep</i><i>Policy check</i><b>Trust<br />layer</b></div><small>{rand(3,7,12)} fictional agents · no unrestricted tool access</small></div>;
  if (section === "Evidence") return <div className="unique-graphic evidence-graphic"><p>INTEGRITY-LINKED EVIDENCE CHAIN</p><div className="evidence-chain"><span>Source</span><b>→</b><span>Provenance</span><b>→</b><span>Conflict</span><b>→</b><span>Record</span></div><div className="hash-lines"><i /><i /><i /><i /></div><small>Fictional chain status: intact and challengeable</small></div>;
  if (section === "MCP Gateway") return <div className="unique-graphic gateway-graphic"><p>GOVERNED MCP TOPOLOGY</p><div className="gateway-map"><span>Agent</span><b>Trust<br />Gateway</b><span>Tool<br />registry</span><span>Audit<br />record</span></div><small>{rand(3,8,14)} synthetic tools exposed · every call evaluated</small></div>;
  return <div className="unique-graphic reports-graphic"><p>OVERSIGHT REPORT BOARD</p><div className="report-sheets"><span><b>Policy</b><i /></span><span><b>Review</b><i /></span><span><b>Evidence</b><i /></span></div><div className="report-bars"><i style={{height:`${rand(35,88,16)}%`}} /><i style={{height:`${rand(35,88,17)}%`}} /><i style={{height:`${rand(35,88,18)}%`}} /><i style={{height:`${rand(35,88,19)}%`}} /></div></div>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
